server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cqrs
      username: root
      password: root
      authentication-database: admin
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin
  redis:
    host: localhost
    port: 6379