server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cqrs?serverTimezone=UTC&characterEncoding=UTF-8
    password: test
    username: test
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  rabbitmq:
    addresses: localhost
    port: 5672
    username: admin
    password: admin